language: go

go:
  - 1.4

env:
  global:
    - secure: "jt2nSMG1JGbAW+YgA19Th5Y4zGhvDbbTCFZIuLArXy37W95PI4H/ckTEk9imSVbnx/mapdwFdzQb0kQVAdsVj75MaqGAxDYupEvDJjEjNJURp944rjoYGlLVbIgPU7EJzf1s3/hBtAcyasDQrCLWHCVKtSBwNQxDMJPLH7wUkOTwKg/wk56e9Fq/1UjaEu4wrzJlTruezHBMJ9/vI1duFzD0NloFXyPFjZ8HKr72a4lGvFi8f2FQYYbCGFFweESxXz41cbBxTkcCNJFc4htoSS4I14tdMsLxOE5sM5rfxhV0YSNeioIQ1hISHA4afe4JkGasOc6dpr+Gtso9QNWvV9EyOTnkkOcHBDlS1Zh0ZpzBB2VAXy8ca//Za/meMIDLgIEVohvzx5Eux3clpSwFq28gIhnBjBYcQ2c6nCEnmxPHvpgjEf8adA46zbaN/Zou1BwiKIAcMmGxitGAbMgRJd0dRy0YDLdqUTR8z/Fj8DxZqw+una1y3TGobtek3UOM8sfocXnTl5qDc47Rp46qm9tgep8w31c9R7vqZQQAT1oM4/T435k0hC8kCbIM1MS+LvWup8031n19hIIJQG1z39Np9CfgZCJ0bPKCGhWmS/QYddnybhgsSjVoQFyF/RsCM8wNYO1+xC25kE6JXeP11Y5Uoh4L+P48bzDbQyXfuho="
    - secure: "XZ1wD8TaiRCNJcfMhmHMopOyIFm5jdSJDbbc1ZUtSwkzMWs1n8QZpTn5E7faUO3lY2W+IPiedag8nH26R0o+9pWDhafVt1CU0C2mMK23e/uCYHbwkT8VtW/rnKa3imdRBkEkZIehcC7bm8/+cDqwxbffIv9hmV0EIu3BkD9awENYNNlcEqq2vuKrfq6tto4iX1ipsXD4zRjaEFwZ/aFM1jQsKsYg4mD+ucuE24kg2oem2uXdYy+IRvRdOmpjZx2eNu2fG/eElv7/06KJ3TLsMTBbhHv6fkLZuN0wczYdUbUpMGystrP5xkt+h8yptf7ZdRV7HgrJ5BXAGLox6HPVWm+3iF6dLz13fCa8RK3gP393OvYkf5gqK+LOEoc0tshKzkPiv77DuU3iIVBLKi92FsVzuKIYWfesy8DgR+lFOLpBYNpZGVyVKT/9OPZOO57dneqqEiI+trEBTtDHjA0vtN+8O3eRDZKT0JrscxTgtrik8ain0HWaU60fMGKcp2XYcHtlZXTnZshKnzrz+zf7JwUx5eDP6fPYvUCoZ/nWMKwtqu/ksrag11Ft2xff2dFwHjVfyRnA2Cryf+5vb7jZtF4jT0JHfkomOC5DsWWrBNMnyl1WHJ8nhAzyfaxv3MKlYEfD3tXctXEJp5w+2yc/qaDO9BXL7r6s5Xru5yi3vuk="

script: go test -v ./...

after_success:
    - "wget http://go-cli.s3-website-us-east-1.amazonaws.com/releases/latest/cf-cli_amd64.deb -qO temp.deb && sudo dpkg -i temp.deb"
    - "rm temp.deb"
    - "cf api https://api.run.pivotal.io"
    - "cf login --u $CF_USERNAME --p $CF_PASSWORD --o jamesclonk.io --s development"
    - "cf push"
    - "cf logout"

notifications:
  email:
    on_success: change
    on_failure: always
